name: mongodb8
services:
  mongo:
    image: mongo:8.0.0-noble
    restart: always
    environment:
      TZ: Asia/Seoul
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - vol_mongodb:/data/db
volumes:
  vol_mongodb: {}